### ISSUE TITLE
Example with Dinosaur

### ISSUE THREAD

**Issue by WillyRamirez** [dabit3/amsterdam-viro-ar#1]
Hi Nader @dabit3 , loved your talk in Amsterdam couple of months ago. I'm actually looking for the example app with the dinosaur in the room, complete with ViroSurface and PlaneSelector and everything. Do you have it here on github? 

Thanks!

**Comment by dabit3** [comment]
Hi Willy, no I do not have a repo for that one, but I know that @vnovick has done quite a few similar (but actually better) demos, maybe he has something open sourced?

Check out this one in particular -> https://github.com/vnovick/chain-react-ar-demo

**Comment by vnovick** [comment]
Thanks @dabit3 for referring.
There is the repo you've mentioned and there is a brand new repo from React Native EU workshop that is actually a full AR game
https://github.com/vnovick/react-native-eu-2018-workshop

**Comment by WillyRamirez** [comment]
Thanks @dabit3 @vnovick  for your demos and your response. I'll have a look at those repo's!
